### ISSUE TITLE
SharePoint page display issues

### ISSUE THREAD

**Issue by ericjia888** [mozziemozz/awesome-docfx-template#2]
Hi Martin Heusser
When I execute this script "BuildDocFxForSPO.ps1" to upload a file to a SharePoint document library, I open the index.aspx home page as follows, and I can't see the TOC, have you encountered this problem?

![image](https://github.com/mozziemozz/awesome-docfx-template/assets/108516877/f4231528-1f40-4df0-bc5c-0df64b2d4e8d)

**Comment by mozziemozz** [comment]
I don't think I have. It's been a while since I created and tested this though. Let me check later and get back to you.

**Comment by ericjia888** [comment]
Okay, thanks for the quick reply.

**Comment by ericjia888** [comment]
@mozziemozz 
Any update on this issue?

Thanks,
Eric Jia

**Comment by mozziemozz** [comment]
No, sorry it will take me some time to test this. Thanks for your understanding.

**Comment by ericjia888** [comment]
No problem, if you are experiencing the same issue please let me know as well, thanks for the time.

**Comment by mozziemozz** [comment]
have you tried to serve the site locally? You probably have the same issue there? I looked at it today and it looks like the new DocFx version creates a new/empty project quite differently so it will require some work from me. I'll implement a required version check of DocFx to make sure that my scripts are working after I tested everything. Thanks for your patience.

**Comment by ericjia888** [comment]
I haven't tried deploying it locally, only on SharePoint Online version. It's probably due to the version differences you mentioned. Since I'm not very familiar with this knowledge, I couldn't identify the specific problem.

**Comment by mozziemozz** [comment]
Hi @ericjia888 I pushed some updates today. Please remove the cloned repo from your system and clone again. Newer DocFx versions use a different init function so I created a default DocFx project using an older version and put that into the repo. `.\Docs` now contains a vanilla version and then the `Initialize-AwesomeDocFx.ps1` applies changes to that.

You'll need to install DocFx Version 2.75.1 for it to work.

**Comment by mozziemozz** [comment]
Hi @ericjia888 I pushed some updates today. Please remove the cloned repo from your system and clone again. Newer DocFx versions use a different init function so I created a default DocFx project using an older version and put that into the repo. `.\Docs` now contains a vanilla version and then the `Initialize-AwesomeDocFx.ps1` applies changes to that.

**Comment by ericjia888** [comment]
Hi Martin Heusser
I've tested it and now this version is working, I'd like to ask if DocFx works with versions greater than 2.75.1 as well? I see that you have added a version check in your code, so if you want to iteratively update DocFx at a later stage it will be affected.

Thanks,
Eric Jia

**Comment by mozziemozz** [comment]
Hi Eric,

If you want to use a newer DocFx version, just update the version which is checked in the script to the version you're using, or remove the check entirely. You only need to run this script when you create a new project/docs site. After that, you can use a newer version to build the site.

**Comment by ericjia888** [comment]
Okay, thanks for your help.

**Comment by ericjia888** [comment]
Hi Martin Heusser
Do you know where the assignment logic for the docurl parameter is?
See that it's pointing to your GitHub URL.

![image](https://github.com/mozziemozz/awesome-docfx-template/assets/108516877/bc2e245d-61cf-4480-8a0e-aa4bb2a6aad2)
![image](https://github.com/mozziemozz/awesome-docfx-template/assets/108516877/a58fb4af-4f1c-42f9-a535-2a8c4b94308f)

**Comment by ericjia888** [comment]
Hi Martin Heusser
Do you know where the assignment logic for the docurl parameter is?
See that it's pointing to your GitHub URL.

![image](https://github.com/mozziemozz/awesome-docfx-template/assets/108516877/bc2e245d-61cf-4480-8a0e-aa4bb2a6aad2)
![image](https://github.com/mozziemozz/awesome-docfx-template/assets/108516877/a58fb4af-4f1c-42f9-a535-2a8c4b94308f)
